#! /bin/sh

sxhkd &

{% if yadm.hostname == "openair" %}
bspc monitor DVI-D-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X
{% else %}
bspc monitor -d I II III IV V VI VII VIII IX X
{% endif %}

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	true

bspc config focus_follows_pointer true

# Window rules:
bspc rule -a "Origin" state=floating
bspc rule -a "Emacs" state=tiled
