#! /bin/sh

sxhkd &

{% if yadm.hostname == "openair" %}
bspc monitor DisplayPort-2 -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X
{% else %}
bspc monitor -d I II III IV V VI VII VIII IX X
{% endif %}

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
