#! /bin/sh

sxhkd &

if [[ "$(hostname)" = "openair" ]]; then
  bspc monitor DVI-D-0 -d I II III IV V
  bspc monitor HDMI-A-0 -d VI VII VIII IX X
elif [[ "$(hostname)" = "carbon" ]]; then
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	true

bspc config focus_follows_pointer true

# Window rules:
bspc rule -a "Origin" state=floating
bspc rule -a "Emacs" state=tiled
